"""Init

Revision ID: b61358ceefcc
Revises: 
Create Date: 2019-02-18 22:36:46.395351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61358ceefcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FileContents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RevokedTokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageId', sa.Integer(), nullable=True),
    sa.Column('firstName', sa.String(length=64), nullable=False),
    sa.Column('lastName', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_firstName'), 'users', ['firstName'], unique=False)
    op.create_index(op.f('ix_users_lastName'), 'users', ['lastName'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pricePerDay', sa.Float(), nullable=False),
    sa.Column('bail', sa.Float(), nullable=False),
    sa.Column('imageId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('availabilityOn', sa.Integer(), nullable=False),
    sa.Column('searchName', sa.Text(), nullable=False),
    sa.Column('searchDescription', sa.Text(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('isBooked', sa.Boolean(), nullable=False),
    sa.Column('bookedFor', sa.Integer(), nullable=True),
    sa.Column('offerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offerId'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offerId')
    )
    op.create_index(op.f('ix_availabilities_isBooked'), 'availabilities', ['isBooked'], unique=False)
    op.create_index(op.f('ix_availabilities_userId'), 'availabilities', ['userId'], unique=False)
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offerId'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offerId')
    )
    op.create_index(op.f('ix_parameters_key'), 'parameters', ['key'], unique=False)
    op.create_index(op.f('ix_parameters_value'), 'parameters', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameters_value'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_key'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_availabilities_userId'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_isBooked'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_table('offers')
    op.drop_index(op.f('ix_users_lastName'), table_name='users')
    op.drop_index(op.f('ix_users_firstName'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('RevokedTokens')
    op.drop_table('FileContents')
    # ### end Alembic commands ###
