"""empty message

Revision ID: de3a9ee47e45
Revises: 92841eb1b2e0
Create Date: 2019-02-12 23:36:58.148529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3a9ee47e45'
down_revision = '92841eb1b2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('pricePerDay', sa.Float(), nullable=False),
    sa.Column('bail', sa.Float(), nullable=False),
    sa.Column('imageId', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('availabilityOn', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('isBooked', sa.Boolean(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offerId'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offerId')
    )
    op.create_index(op.f('ix_availabilities_isBooked'), 'availabilities', ['isBooked'], unique=False)
    op.create_index(op.f('ix_availabilities_userId'), 'availabilities', ['userId'], unique=False)
    op.create_table('parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('offerId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offerId'], ['offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offerId')
    )
    op.create_index(op.f('ix_parameters_key'), 'parameters', ['key'], unique=False)
    op.create_index(op.f('ix_parameters_value'), 'parameters', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameters_value'), table_name='parameters')
    op.drop_index(op.f('ix_parameters_key'), table_name='parameters')
    op.drop_table('parameters')
    op.drop_index(op.f('ix_availabilities_userId'), table_name='availabilities')
    op.drop_index(op.f('ix_availabilities_isBooked'), table_name='availabilities')
    op.drop_table('availabilities')
    op.drop_table('offers')
    # ### end Alembic commands ###
